version: '3.7'

networks:
  traefik-public:
    external: true
    
services:  
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - traefik-public
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin   

############ phpmyadmim ############
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_HOST=mysql
      - TZ=America/Maceio
    ports:
      - '9090:80'
    depends_on:
      - mysql
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      ## HTTP Routers
      - traefik.http.routers.phpmyadmin-rtr.entrypoints=web
      # - traefik.http.routers.phpmyadmin-rtr.entrypoints=websecure
      - traefik.http.routers.phpmyadmin-rtr.rule=Host(`phpmyadmin.localhost`)
      - traefik.http.routers.phpmyadmin-rtr.tls=true
      # - traefik.http.routers.phpmyadmin-rtr.tls.certresolver=letsencrypt
      ## HTTP Services
      - traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80
